### PR TITLE
refactor(js,core): decode resource dynamically from access token on saving tokens

### PR DESCRIPTION
**Pull request by charIeszhao**
## Summary

* Dynamically decode resource indicator from access token when persisting it in storage
* Use `decodeJwt` from `jose` library to decode claims from id token and access token

## Testing

- [x] Passed all unit tests

### CODE REVIEW

**Review by wangsijie — COMMENTED** [review]
What can we benefit from this change?

**Comment by charIeszhao** [comment]
> What can we benefit from this change?

There is a case that the resource indicator you pass on `getAccessToken` could be different from the audience that encoded in the accessToken.

With this change, we can guarantee the resource we use in the access token map is the same resource that access token is issued with.

**Comment by wangsijie** [comment]
I got it, thanks @charIeszhao

**Comment by charIeszhao** [comment]
> I got it, thanks @charIeszhao

Hmmm, after you asking me, I re-think about this and now I feel it might not be the right thing to do. Let's put this on hold for now.

**Comment by gao-sun** [comment]
should we close this? @charIeszhao

**Comment by charIeszhao** [comment]
> should we close this? @charIeszhao 

Yeah, I think we should, as per our discussion this is not needed anymore.

**Pull request closed without merging**
